### ISSUE TITLE
How does one use a .7z file?

### ISSUE THREAD

**Issue by lilbuzz** [RalphBacon/264-Dot-Matrix-LED-World-Clock-and-Messaging#1]
The contents of the code Zip file are a file with extension .7z - what do I do with that?

**Comment by RalphBacon** [comment]
A .7z file type has been created by the compression utility 7-zip, and should be understood by your OS. If not, download 7-zip, it's free, right click the archive and extract to a folder of your choice.

I use 7-zip because it is much faster than the ubiquitous .zip format, but it can extract those too. Win win!
